language: python
python:
- '2.7'
env:
  global:
  - W2_DATABASE_HOST=127.0.0.1
  - W2_DATABASE_PASSWORD=
  - W2_DATABASE_USER=root
  - W2_SECRET_KEY=`head /dev/urandom | sha256sum`
before_install:
- printenv W2_DATABASE_HOST
- printenv W2_DATABASE_PASSWORD
- printenv W2_DATABASE_USER
- cat /etc/os-release
install: pip install -r requirements.txt
script:
- coverage run --source=. manage.py test -v 2
- coverage xml
- if [ "$CODACY_PROJECT_TOKEN" ]; then python-codacy-coverage -r coverage.xml; fi
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: LRuBdelPHheZTzy275pa2Bhn/gYg5C91rIOAQz26yVyfIfU5aaMbNjROK2m2EpPN+yuMCtVQk/NkQqj4xNUdnqSXBwkmrt1NUbCSL5PJREqNlzqDJYRg445IP47OCWGOIZR5TxGaKNQFSgF7S8Z0dKuG9cipVtvTXqQBf3kFp4s=
  app:
    development: wasa2il-development
    master: wasa2il-staging
  run:
  - python manage.py compilemessages
after_success:
- "./tag.sh"
