# Usage:
# docker-compose up
# Then migrate the database: (you might need to run it twice)
# docker-compose run wasaweb python manage.py migrate
version: '2'

services:
  wasaweb:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - "db"
    depends_on:
      - db
    environment:
      - W2_DATABASE_HOST=db
      - W2_DATABASE_NAME=wasa2il
      - W2_DATABASE_PASSWORD=wasa2il
      - W2_DATABASE_PORT=3306
      - W2_DATABASE_USER=wasa2il
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=wasa2il
      - MYSQL_DATABASE=wasa2il
      - MYSQL_USER=wasa2il
      - MYSQL_PASSWORD=wasa2il
    # This makes the port OPEN on the server.
    # Disable in production!
    ports:
      - "3306:3306"
