# Generated by Django 5.1 on 2024-08-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20231130_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='special_process',
            field=models.CharField(blank=True, choices=[(None, '---'), ('accepted_at_assembly', 'Accepted at assembly'), ('rejected_at_assembly', 'Rejected at assembly'), ('retracted', 'Retracted')], default='', max_length=32, null=True, verbose_name='Special process'),
        ),
    ]
