# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          #MYSQL_DATABASE: laravel_tags
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mysqlclient
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        manage.py test -v 2
      env:
        W2_DATABASE_HOST: 127.0.0.1
        W2_DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        W2_DATABASE_PASSWORD:
        W2_DATABASE_USER: root
        W2_SECRET_KEY: supersecretkey-only-used-for-testing

    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'wasa2il-development'
        heroku_email: ${{ secrets.MY_EMAIL }}
        branch: 'development'
